# DSE Course 1, Session 3: Functions and Pandas Introduction

**Instructor**: Wesley Beckner<br>

**Contact**: wesleybeckner@gmail.com

<br>

---

<br>

Today, we will discuss **_functions_** in more depth.  We've seen them previously and used them, for example the `.append()` **_function_** for lists, or the even more general `print()` function.  Here, we'll dig into how you can make your own functions to encapsulate code that you will reuse over and over.  

Then we'll jump into the **Pandas** package.  Packages are collections of related functions.  These are the things we `import`. Pandas is a two dimensional data structure like a spreadsheet in Excel. In fact, we will be importing our first dataset and viewing it, with Pandas!

<br>

---

## 3.0 Review from Session on Data Structures and Flow Control

In our last session, we discussed **_lists_**, **_dictionaries_**, and **_flow control_**.

**_Lists_** are **_ordered collections_** of data that can be used to hold multiple pieces of information while preserving their order.  We use `[` and `]` to access elements by their indices which start with `0`.  All things that operate on **_lists_** like slices use the concept of an inclusive lower bound and an exclusive upper bound.  So, the following gets elements from the **_list_** `my_list` with index values of `0`, `1`, and `2`, but **not** `3`!

```
my_list[0:3]
```

> What other way is there of writing the same statement using **_slicing_**?  Hint, think about leaving out one of the numbers in the slice!

**_Dictionaries_** are **_named_** **_collections_** of data that can be used to hold multiple pieces of information as **_values_** that are addressed by **_keys_** resulting in a **_key_** to **_value_** data structure.  They are accessed with `[` and `]` but intialized with `{` and `}`.  E.g.

```
my_dict = { 'cake' : 'Tasty!', 'toenails' : 'Gross!' }
my_dict['cake']
```

Finally, we talked about **_flow control_** and using the concept of **_conditional execution_** to decide which code statements were executed.  Remember this figure?

<img src="https://docs.oracle.com/cd/B19306_01/appdev.102/b14261/lnpls008.gif">Flow control figure</img>

> What are the **_if_** statments? <br> 
Where do **_for_** loops fit in? <br>

## 3.1 Functions

For loops let you repeat some code for every item in a list.  Functions are similar in that they run the same lines of code and, frequently, for new values of some variable (we call these **_parameters_**).  They are different in that functions are not limited to looping over items.

Functions are a critical part of writing easy to read, reusable code.

Create a function like:
```
def function_name (parameters):
    """
    optional docstring
    """
    function expressions
    return [variable]
```

Here is a simple example.  It prints a string that was passed in and returns nothing.

```
def print_string(string):
    """This prints out a string passed as the parameter."""
    print(string)
    return
```

In [2]:
def print_string(string):
  """This prints out a string passed as the parameter"""
  print(string)
  return

To call the function, use:
```
print_string("GIX is awesome!")
```

_Note:_ The function has to be defined before you can call it!

In [3]:
print_string("GIX is awesome!")

GIX is awesome!

### 3.1.1 Reserved words: def, return, and yield

Notice the highlighted words in our function definition: `def` and `return` these are *reserved words* in python used to define functions. Every function definition requires these reserved words. `yield` is another reserved word that is similar to `return` but operates slightly differently. It is beyond the scope of what we are covering in this session. This tutorial from [realpython](https://realpython.com/introduction-to-python-generators/) has good information on the topic.

In [7]:
# what is return doing in this function?
def my_square(a):
  return a ** 2

`return` is going to output whatever value(s) follow after the keyword `return` when we call upon our function

In [9]:
a = 2
my_square(a)

4

I'm going to return two values...

In [10]:
def my_square(a):
  return a ** 2, a

and we see how the output updates accordingly

In [11]:
my_square(a)

(4, 2)

We can capture these values on the output with...

In [12]:
square, new_a = my_square(a)

In [13]:
print(square, new_a)

4 2

### 3.1.2 Global vs local variables and function parameters

In a function, new variables that you create are not saved when the function returns - these are **_local_** variables.  Variables defined outside of the function can be accessed but not changed - these are **_global_** variables.

let's define the following function

In [14]:
def my_little_func(a):
  b = 10
  return a * b

In [15]:
my_little_func(2)

20

if I run the following...

In [17]:
# b

Let's play with this a little further...

...now let's define b outside the function and call our function with `a=5`

In [25]:
# what happens here?
b = 100
my_little_func(5)

50

we see that b is still 100, instead of 10 as its defined within the function. This is because b inside of `my_little_func` is a *local* variable.

it doesn't matter how I define b outside the function because within the function it is set locally.

... Let's do this A LITTLE MORE

In [23]:
def my_new_func(a):
  print(b)
  return a*b

now if I call on my new function, because `b` is not defined locally within the function, it takes on the global value. 

This is typically not happy happy fun fun behavior for us, we want to be explicit about how we define and use our variables (but there are some times when this is appropriate to do)

In [24]:
b= 1e4 # side note, what did I do here????
my_new_func(a)

10000.0

20000.0

#### 3.1.1.1 Function Parameters

Parameters (or arguments) in Python are all passed by reference.  This means that if you modify the parameters in the function, they are modified outside of the function. (Enrichment: Exceptions, see below)

See the following example:

```
def change_list(my_list):
   """This changes a passed list into this function"""
   my_list.append('four');
   print('list inside the function: ', my_list)
   return

my_list = [1, 2, 3];
print('list before the function: ', my_list)
change_list(my_list);
print('list after the function: ', my_list)
```

In [26]:
def change_list(my_list):
   """This changes a passed list into this function"""
   my_list.append('four');
   print('list inside the function: ', my_list)
   return

my_list = [1, 2, 3];
print('list before the function: ', my_list)
change_list(my_list);
print('list after the function: ', my_list)

list before the function:  [1, 2, 3]
list inside the function:  [1, 2, 3, 'four']
list after the function:  [1, 2, 3, 'four']

#### 3.1.1.2 Enrichment: Global, local, and immutables

Let's go back to our former example...

immutables:

* integers, float, str, tuples

In [53]:
b = "a string"
b = 10
b = 10.2
b = (10, 2)
b = [10, 2]
a = 2

def my_little_func(a, b):
  if type(b) == str:
    b += "20"
  elif (type(b) == int) or (type(b) == float):
    b += 10
  elif (type(b) == tuple):
    print("AYYY no tuple changes, Dude")
    pass
  elif (type(b) == list):
    b.append('whoaaaa')
  print(b)
  return

print(b)
my_little_func(a, b)
print(b)

[10, 2]
[10, 2, 'whoaaaa']
[10, 2, 'whoaaaa']

There is a way to change a global variable within a function with the **_global_** keyword.  Generally, the use of **_global_** variables is not encouraged, instead use parameters. We won't cover the global keyword here but you can [explore further](https://www.programiz.com/python-programming/global-keyword) on your own if you are interested.

In [45]:
b = 10
a = 2

def my_little_func(a):
  global b
  b += 20
  print(b)
  return 

print(b)
my_little_func(a)
print(b)

10
30
30

#### Exercise 1: My first function

Write a function that takes one parameter and returns any data structure

> If you are going to return multiple objects, what data structure that we talked about can be used?  Give and example below.

In [55]:
# Cell for excerise 1

### 3.1.3 Parameter types

**Function calling:**

* positional 
    * `func(10, 20)`
* keyword
    * `func(a=10, b=20)` or `func(b=20, a=10)`

**Function writing:**
* default
    * `def func(a=10, b=20)`

```
def print_name(first, last='Beckner'):
    print(f'Your name is {first} {last}')
    return
```

In [58]:
def print_name(first, last='Beckner'):
    print("Your name is {} {}".format(first, last))
    return

In [60]:
print_name(last='Beckner', first='Wesley')

Your name is Wesley Beckner

Play around with the above function.

In [ ]:
print_name('Wesley', last='the DSE Instructor')

Your name is Wesley the DSE Instructor

Functions can contain any code that you put anywhere else including:
* `if`...`elif`...`else`
* `for`...`while`
* other function calls

```
def print_name_age(first, last, age):
    print_name(first, last)
    print('Your age is %d' % (age))
    if age > 25 and age < 40:
        print('You are a millenial!')
    return
```

In [61]:
def print_name_age(first, last, age):
    print_name(first, last)
    print('Your age is %d' % (age))
    if age > 25 and age < 40:
        print('You are a millenial!')
    return

```
print_name_age(age=29, last='Beckner', first='Wesley')
```

In [62]:
print_name_age(age=29, last='Beckner', first='Wesley')

Your name is Wesley Beckner
Your age is 29
You are a millenial!

## 3.2 The scientific python stack

In addition to Python's built-in modules like the ``math`` module we explored above, there are also many often-used third-party modules that are core tools for doing data science with Python.
Some of the most important ones are:

#### [``numpy``](http://numpy.org/): Numerical Python

Numpy is short for "Numerical Python", and contains tools for efficient manipulation of arrays of data.
If you have used other computational tools like IDL or MatLab, Numpy should feel very familiar.

#### [``scipy``](http://scipy.org/): Scientific Python

Scipy is short for "Scientific Python", and contains a wide range of functionality for accomplishing common scientific tasks, such as optimization/minimization, numerical integration, interpolation, and much more.
We will not look closely at Scipy today, but we will use its functionality later in the course.

#### [``pandas``](http://pandas.pydata.org/): Labeled Data Manipulation in Python

Pandas is short for "Panel Data", and contains tools for doing more advanced manipulation of labeled data in Python, in particular with a columnar data structure called a *Data Frame*.
If you've used the [R](http://rstats.org) statistical language (and in particular the so-called "Hadley Stack"), much of the functionality in Pandas should feel very familiar.

#### [``matplotlib``](http://matplotlib.org): Visualization in Python

Matplotlib started out as a Matlab plotting clone in Python, and has grown from there in the 15 years since its creation. It is the most popular data visualization tool currently in the Python data world (though other recent packages are starting to encroach on its monopoly).

#### [``scikit-learn``](https://scikit-learn.org/stable/): Machine Learning in Python

Scikit-learn is a machine learning library.

It features various classification, regression, and clustering algorithms, including support vector machines, random forests, gradient boosting, k-means, and DBSCAN.

The library is designed to interoperate with the Python numerical and scientific libraries NumPy and SciPy.

As a side note, every year stack overflow conducts a developer survey. Pandas is the fourth most popular miscellaneous framework among developers, out of all common coding languages!

<img src="https://raw.githubusercontent.com/wesleybeckner/ds_for_engineers/main/assets/other_frameworks_description.JPG" width=400px></img>

<img src="https://raw.githubusercontent.com/wesleybeckner/ds_for_engineers/main/assets/other_frameworks_results.JPG" width=400px></img>

<small>source: insights.stackoverflow.com/survey/2020</small>

## 3.3 Pandas

### 3.3.1 Pandas and Scikit-Learn `load_datasets`

We begin by loading the Panda's package.  Packages are collections of functions that share a common utility.  We've seen `import` before.  Let's use it to import Pandas and all the richness that pandas has.

We'll also use a very useful feature of the scikit-learn toolkit, the `load_datasets` module. We will do some very rudimentary tasks with this dataset, just to demonstrate the utility of `load_datasets`, then we will switch over to a more relevant dataset for our purposes.

```
import pandas
from sklearn.datasets import load_wine
```

In [63]:
import pandas
from sklearn.datasets import load_wine

We import a function `load_wine` that loads a simple data set we can play with called the Wine recognition dataset from the 1980s.

You can read more about that dataset [here](https://archive.ics.uci.edu/ml/datasets/Wine)

```
dataset = load_wine()
print(dataset.DESCR)
```

In [99]:
dataset = load_wine()
print(dataset.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2

    :Summary Statistics:

    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Magnesium:                    70.0 162.0    99.7  14.3
    Total Phenols:                0.98  3.88    2.29  0.63
    Flavanoids:                   0.34  5.08    2.03  1.00
    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12
    Proanthocyanins:              0.41  3.58    1.59  0.57
    Colour Intensity:              1.3  13.0     5.1   2.3
    Hue:                          0.48  1.71    0.96  0.23
    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71
    Proline:                       278  1680     746   315
    ============================= ==== ===== ======= =====

    :Missing Attribute Values: None
    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

This is a copy of UCI ML Wine recognition datasets.
https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data

The data is the results of a chemical analysis of wines grown in the same
region in Italy by three different cultivators. There are thirteen different
measurements taken for different constituents found in the three types of
wine.

Original Owners:

Forina, M. et al, PARVUS -
An Extendible Package for Data Exploration, Classification and Correlation.
Institute of Pharmaceutical and Food Analysis and Technologies,
Via Brigata Salerno, 16147 Genoa, Italy.

Citation:

Lichman, M. (2013). UCI Machine Learning Repository
[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,
School of Information and Computer Science.

.. topic:: References

  (1) S. Aeberhard, D. Coomans and O. de Vel,
  Comparison of Classifiers in High Dimensional Settings,
  Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of
  Mathematics and Statistics, James Cook University of North Queensland.
  (Also submitted to Technometrics).

  The data was used with many others for comparing various
  classifiers. The classes are separable, though only RDA
  has achieved 100% correct classification.
  (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data))
  (All results using the leave-one-out technique)

  (2) S. Aeberhard, D. Coomans and O. de Vel,
  "THE CLASSIFICATION PERFORMANCE OF RDA"
  Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of
  Mathematics and Statistics, James Cook University of North Queensland.
  (Also submitted to Journal of Chemometrics).

```
df = pandas.DataFrame()
```

In [100]:
df = pandas.DataFrame()

#### 3.3.1.1 import ... as ... pattern

Because we'll use it so much, we often import under a shortened name using the ``import ... as ...`` pattern:

```
import pandas as pd
```

In [101]:
import pandas as pd

### 3.3.2 Creating pandas dataframes

Let's create an empty _data frame_ and put the result into a variable called `df`.  This is a popular choice for a _data frame_ variable name.

```
df = pd.DataFrame()
```

In [102]:
df = pd.DataFrame()

Let's open the Wine dataset as a pandas data frame.  Notice we change the value of the `df` variable to point to a new data frame.

```
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)
```

In [103]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

#### 3.3.2.1 From excel and csv

Please follow this [link](https://raw.githubusercontent.com/wesleybeckner/ds_for_engineers/main/data/truffle_margin/margin_data.csv)

This is what we call a csv or comma separated value file. We have a method reading these directly into pandas:

In [72]:
pd.read_csv('https://raw.githubusercontent.com/wesleybeckner/ds_for_engineers/main/data/truffle_margin/margin_data.csv')

     Base Cake  ...                                            Product
0     Tiramisu  ...  Tiramisu-Chocolate Outer-Doughnut-Egg Nog-Amet...
1     Tiramisu  ...  Tiramisu-Chocolate Outer-Doughnut-Egg Nog-Amet...
2     Tiramisu  ...  Tiramisu-Chocolate Outer-Chocolate-Pear-Amethy...
3     Tiramisu  ...  Tiramisu-Chocolate Outer-Doughnut-Egg Nog-Amet...
4     Tiramisu  ...  Tiramisu-Chocolate Outer-Doughnut-Rock and Rye...
...        ...  ...                                                ...
2501    Butter  ...  Butter-Chocolate Outer-Lemon Bar-Wild Cherry C...
2502    Butter  ...  Butter-Chocolate Outer-Cream Soda-Peppermint-A...
2503    Butter  ...  Butter-Jelly Filled-Orange-Cucumber-Burgundy-9...
2504    Butter  ...  Butter-Chocolate Outer-Horchata-Dill Pickle-Am...
2505    Butter  ...  Butter-Candy Outer-Ginger Lime-Vanilla-Amethys...

[2506 rows x 10 columns]

In [125]:
df = pd.read_csv("https://raw.githubusercontent.com/wesleybeckner/ds_for_engineers/main/data/wine_quality/winequalityN.csv")

We can do this in a similar way with excel files.

In [74]:
pd.read_excel('https://raw.githubusercontent.com/wesleybeckner/ds_for_engineers/main/data/truffle_margin/margin_data.xlsx')

     Base Cake  ...                                            Product
0     Tiramisu  ...  Tiramisu-Chocolate Outer-Doughnut-Egg Nog-Amet...
1     Tiramisu  ...  Tiramisu-Chocolate Outer-Doughnut-Egg Nog-Amet...
2     Tiramisu  ...  Tiramisu-Chocolate Outer-Chocolate-Pear-Amethy...
3     Tiramisu  ...  Tiramisu-Chocolate Outer-Doughnut-Egg Nog-Amet...
4     Tiramisu  ...  Tiramisu-Chocolate Outer-Doughnut-Rock and Rye...
...        ...  ...                                                ...
2501    Butter  ...  Butter-Chocolate Outer-Lemon Bar-Wild Cherry C...
2502    Butter  ...  Butter-Chocolate Outer-Cream Soda-Peppermint-A...
2503    Butter  ...  Butter-Jelly Filled-Orange-Cucumber-Burgundy-9...
2504    Butter  ...  Butter-Chocolate Outer-Horchata-Dill Pickle-Am...
2505    Butter  ...  Butter-Candy Outer-Ginger Lime-Vanilla-Amethys...

[2506 rows x 10 columns]

#### 3.3.2.2 from lists

In [75]:
my_list = [[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]]
pd.DataFrame(my_list)

   0  1  2
0  1  2  3
1  3  4  5
2  5  6  7
3  7  8  9

In [76]:
pd.DataFrame([[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]],
                   index=['a', 'b', 'c', 'd'], columns=['x', 'y', 'z'])

   x  y  z
a  1  2  3
b  3  4  5
c  5  6  7
d  7  8  9

#### 3.3.2.3 from dictionaries

In [87]:
from_dict = pd.DataFrame({'A': ['apple', 'airplane'], 'B': ['bannana', 'bubbles']})
from_dict

          A        B
0     apple  bannana
1  airplane  bubbles

In [85]:
from_dict.to_dict()

{'A': {0: 'apple', 1: 'airplane'}, 'B': {0: 'bannana', 1: 'bubbles'}}

#### 3.3.2.4 on `pandas.Series`

pandas `Series` objects will percolate in our experience here and there, however they are not so important as for us to wish to spend dedicated time on them. For now, know that they are a lower-level data collection in the pandas framework. You can think of them as an individual column or row in the pandas dataframe. For more practice with these you can refer to [this documentation]()

### 3.3.3 Viewing pandas dataframes

The ``head()`` and ``tail()`` methods show us the first and last rows of the data.

```
df.head()
df.tail()
```

In [126]:
df.head()

    type  fixed acidity  volatile acidity  ...  sulphates  alcohol  quality
0  white            7.0              0.27  ...       0.45      8.8        6
1  white            6.3              0.30  ...       0.49      9.5        6
2  white            8.1              0.28  ...       0.44     10.1        6
3  white            7.2              0.23  ...       0.40      9.9        6
4  white            7.2              0.23  ...       0.40      9.9        6

[5 rows x 13 columns]

In [127]:
df.tail()

     type  fixed acidity  volatile acidity  ...  sulphates  alcohol  quality
6492  red            6.2             0.600  ...       0.58     10.5        5
6493  red            5.9             0.550  ...        NaN     11.2        6
6494  red            6.3             0.510  ...       0.75     11.0        6
6495  red            5.9             0.645  ...       0.71     10.2        5
6496  red            6.0             0.310  ...       0.66     11.0        6

[5 rows x 13 columns]

The ``shape`` attribute shows us the number of elements:

```
df.shape
```

Note it doesn't have the `()` because it isn't a **_function_** - it is an **_attribute_** or variable attached to the `df` object.

In [128]:
df.shape

(6497, 13)

The ``columns`` attribute gives us the column names

```
df.columns
```

In [129]:
df.columns

Index(['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

The ``index`` attribute gives us the index names

```
df.index
```

In [130]:
df.index

RangeIndex(start=0, stop=6497, step=1)

The ``dtypes`` attribute gives the data types of each column, remember the data type *_floating point_**?:

```
df.dtypes
```

In [131]:
df.dtypes

type                     object
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [132]:
df.describe()

       fixed acidity  volatile acidity  ...      alcohol      quality
count    6487.000000       6489.000000  ...  6497.000000  6497.000000
mean        7.216579          0.339691  ...    10.491801     5.818378
std         1.296750          0.164649  ...     1.192712     0.873255
min         3.800000          0.080000  ...     8.000000     3.000000
25%         6.400000          0.230000  ...     9.500000     5.000000
50%         7.000000          0.290000  ...    10.300000     6.000000
75%         7.700000          0.400000  ...    11.300000     6.000000
max        15.900000          1.580000  ...    14.900000     9.000000

[8 rows x 12 columns]

### 3.3.4 Manipulating data with ``pandas``

Here we'll cover some key features of manipulating data with pandas

#### 3.3.4.1 Selection

Access columns by name using square-bracket indexing:

```
df['alcohol']
```

In [135]:
df['alcohol']

0        8.8
1        9.5
2       10.1
3        9.9
4        9.9
        ...
6492    10.5
6493    11.2
6494    11.0
6495    10.2
6496    11.0
Name: alcohol, Length: 6497, dtype: float64

Mathematical operations on columns happen *element-wise*:

```
df['alcohol'] * .01
```

In [136]:
df['alcohol'] * .01

0       0.088
1       0.095
2       0.101
3       0.099
4       0.099
        ...
6492    0.105
6493    0.112
6494    0.110
6495    0.102
6496    0.110
Name: alcohol, Length: 6497, dtype: float64

Columns can be created (or overwritten) with the assignment operator.
Let's create a alcohol fraction column.

```
df['alcohol fraction'] = df['alcohol'] * .01
```

In [137]:
df['alcohol fraction'] = df['alcohol'] * .01

Let's use the `.head()` **_function_** to see our new data!

```
df.head()
```

In [138]:
df.head()

    type  fixed acidity  volatile acidity  ...  alcohol  quality  alcohol fraction
0  white            7.0              0.27  ...      8.8        6             0.088
1  white            6.3              0.30  ...      9.5        6             0.095
2  white            8.1              0.28  ...     10.1        6             0.101
3  white            7.2              0.23  ...      9.9        6             0.099
4  white            7.2              0.23  ...      9.9        6             0.099

[5 rows x 14 columns]

##### 3.3.4.1.1 `loc` and `iloc`

Pandas provides a powerful way to work with both rows and columns together, optionally using their label indices or numeric indices.

- **`.loc :`**<br/>
Purely label-location based indexer for selection by label (but may also be used with a boolean array).<br/>
  **Important: If you use slicing in loc, it will return the end index as well**
  

- **`.iloc:`**<br/>
Purely integer-location based indexing for selection by position (but may also be used with a boolean array).

In [139]:
df.columns[1]

'fixed acidity'

In [140]:
df.loc[:5:2, [df.columns[1]]]

   fixed acidity
0            7.0
2            8.1
4            7.2

In [141]:
df.iloc[-5:, [3,5]]

      citric acid  chlorides
6492         0.08      0.090
6493         0.10      0.062
6494         0.13      0.076
6495         0.12      0.075
6496         0.47      0.067

##### 3.3.4.1.2 column vs index access

In [142]:
df['alcohol'][0:10]

0     8.8
1     9.5
2    10.1
3     9.9
4     9.9
5    10.1
6     9.6
7     8.8
8     9.5
9    11.0
Name: alcohol, dtype: float64

In [143]:
# df[0]['alcohol'] # will return an error

In [144]:
my_list = [[10, 20, 30]]*4
mydf = pd.DataFrame(my_list, 
                    index=['a','b','c','d'], 
                    columns=['alpha', 'beta', 'gamma'])
mydf

   alpha  beta  gamma
a     10    20     30
b     10    20     30
c     10    20     30
d     10    20     30

In [145]:
mydf.loc['a', 'alpha'] = 'mychange'

In [146]:
# using this you will get a setting
# with copy warning (depending on your pandas
# warning settings)
# mydf['alpha']['a'] = 'newchange'

You want to use `loc` or `iloc` when setting new values to pandas dataframes.

#### 3.3.4.2 Filtering

filtering down your selection will be BIGLY useful in your data quests

##### 3.3.4.2.1 By String

one of the first tools we'll use to filter our dataset is the `.str.contains` method. Let's take an example.

In [147]:
df[df['type'].str.contains('white')]

       type  fixed acidity  ...  quality  alcohol fraction
0     white            7.0  ...        6             0.088
1     white            6.3  ...        6             0.095
2     white            8.1  ...        6             0.101
3     white            7.2  ...        6             0.099
4     white            7.2  ...        6             0.099
...     ...            ...  ...      ...               ...
4893  white            6.2  ...        6             0.112
4894  white            6.6  ...        5             0.096
4895  white            6.5  ...        6             0.094
4896  white            5.5  ...        7             0.128
4897  white            6.0  ...        6             0.118

[4898 rows x 14 columns]

or if you know the exact string you are looking for

In [ ]:
df[df['type'] == 'white']

       type  fixed acidity  volatile acidity  ...  sulphates  alcohol  quality
0     white            7.0              0.27  ...       0.45      8.8        6
1     white            6.3              0.30  ...       0.49      9.5        6
2     white            8.1              0.28  ...       0.44     10.1        6
3     white            7.2              0.23  ...       0.40      9.9        6
4     white            7.2              0.23  ...       0.40      9.9        6
...     ...            ...               ...  ...        ...      ...      ...
4893  white            6.2              0.21  ...       0.50     11.2        6
4894  white            6.6              0.32  ...       0.46      9.6        5
4895  white            6.5               NaN  ...       0.46      9.4        6
4896  white            5.5              0.29  ...       0.38     12.8        7
4897  white            6.0              0.21  ...       0.32     11.8        6

[4898 rows x 13 columns]

##### 3.3.4.2.2 By numerical value

In [151]:
df[df['quality'] > 5]

       type  fixed acidity  ...  quality  alcohol fraction
0     white            7.0  ...        6             0.088
1     white            6.3  ...        6             0.095
2     white            8.1  ...        6             0.101
3     white            7.2  ...        6             0.099
4     white            7.2  ...        6             0.099
...     ...            ...  ...      ...               ...
6490    red            6.3  ...        6             0.110
6491    red            6.8  ...        6             0.095
6493    red            5.9  ...        6             0.112
6494    red            6.3  ...        6             0.110
6496    red            6.0  ...        6             0.110

[4113 rows x 14 columns]

#### 3.3.4.3 Select, filter, operation

The real power of Pandas comes in its tools for grouping and aggregating data. Here we'll look at *value counts* and the basics of *group-by* operations.

In [152]:
# a basic select, filter, operate procedure would look like:
df[df['type'] == 'white']['density'].describe()

count    4898.000000
mean        0.994027
std         0.002991
min         0.987110
25%         0.991723
50%         0.993740
75%         0.996100
max         1.038980
Name: density, dtype: float64

we can invert the selection with `~`

In [153]:
df[~(df['type'] == 'white')]['density'].describe()

count    1599.000000
mean        0.996747
std         0.001887
min         0.990070
25%         0.995600
50%         0.996750
75%         0.997835
max         1.003690
Name: density, dtype: float64

In preparation for grouping the data, let's bin the instances by their density (we could have chosen any numerical column). For that, we'll use ``pd.cut``.  The documentation for ``pd.cut`` can be found [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html). It is used to bin values into discrete intervals.  This is like a histogram where for each *bin* along the range of data values, you count the number of occurrences of that bin.  in our example, we'll use 10 bins and let Pandas decide how to evenly divide the range into the bins.  Let's see it in action.

```
df['density_group'] = pd.cut(df['density'], 10)
df.head()
df.dtypes
```

In [154]:
df['density_group'] = pd.cut(df['density'], 10)

In [155]:
df.head()

    type  fixed acidity  ...  alcohol fraction   density_group
0  white            7.0  ...             0.088  (0.997, 1.003]
1  white            6.3  ...             0.095  (0.992, 0.997]
2  white            8.1  ...             0.101  (0.992, 0.997]
3  white            7.2  ...             0.099  (0.992, 0.997]
4  white            7.2  ...             0.099  (0.992, 0.997]

[5 rows x 15 columns]

In [156]:
df.dtypes

type                      object
fixed acidity            float64
volatile acidity         float64
citric acid              float64
residual sugar           float64
chlorides                float64
free sulfur dioxide      float64
total sulfur dioxide     float64
density                  float64
pH                       float64
sulphates                float64
alcohol                  float64
quality                    int64
alcohol fraction         float64
density_group           category
dtype: object

Pandas includes an array of useful functionality for manipulating and analyzing tabular data.
We'll take a look at two of these here.

The ``pandas.value_counts`` returns statistics on the unique values within each column.

We can use it, for example, to break down the wines by their density group that we just created:

```
pd.value_counts(df['density_group'])
```

In [160]:
pd.value_counts(df['density_group'], sort=False)

(0.987, 0.992]    1599
(0.992, 0.997]    3645
(0.997, 1.003]    1241
(1.003, 1.008]       9
(1.008, 1.013]       2
(1.013, 1.018]       0
(1.018, 1.023]       0
(1.023, 1.029]       0
(1.029, 1.034]       0
(1.034, 1.039]       1
Name: density_group, dtype: int64

What happens if we try this on a continuous valued variable?

```
pd.value_counts(df['density'])
```

In [161]:
pd.value_counts(df['density'])

0.99760    69
0.99720    69
0.99800    64
0.99200    64
0.99280    63
           ..
0.99483     1
0.98947     1
0.99837     1
0.99511     1
0.98923     1
Name: density, Length: 998, dtype: int64

#### Exercise 2: `value_counts, unique, nunique`

We can do a little data exploration with this by seeing how common different values are. Play around with these pandas methods:

* `value_counts()`
* `unique()`
* `nunique()`

Also be sure to use:

* selection
* filteration
* (and you are already using operation with the above mentioned pandas methods, value_counts, unique, nunique (: )

Do so with 3 different columns in the dataframe

In [ ]:
# Cell for Exercise 2

#### 3.3.4.4 Group-by Operation

One of the killer features of the Pandas dataframe is the ability to do group-by operations.
You can visualize the group-by like this (image borrowed from the [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do))

![image](https://swcarpentry.github.io/r-novice-gapminder/fig/12-plyr-fig1.png)

#### 3.3.4.5 Summary statistics with groupby: `value_counts`,  `count`, `describe`

Let's break take this in smaller steps.
Recall our ``density_group`` column.

```
pd.value_counts(df['density_group'])
```

In [162]:
pd.value_counts(df['density_group'])

(0.992, 0.997]    3645
(0.987, 0.992]    1599
(0.997, 1.003]    1241
(1.003, 1.008]       9
(1.008, 1.013]       2
(1.034, 1.039]       1
(1.029, 1.034]       0
(1.023, 1.029]       0
(1.018, 1.023]       0
(1.013, 1.018]       0
Name: density_group, dtype: int64

`groupby` allows us to look at the number of values for each column and each value.  The group by documentation is [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html).  Basically, `groupby` allows us to create *groups* of records based on their values. Let's count how many records, or rows, in our data set fall into each bin of our density data.

```
df.groupby(['density_group']).count()
```

In [163]:
df.groupby(['density_group']).count()

                type  fixed acidity  ...  quality  alcohol fraction
density_group                        ...
(0.987, 0.992]  1599           1597  ...     1599              1599
(0.992, 0.997]  3645           3638  ...     3645              3645
(0.997, 1.003]  1241           1240  ...     1241              1241
(1.003, 1.008]     9              9  ...        9                 9
(1.008, 1.013]     2              2  ...        2                 2
(1.013, 1.018]     0              0  ...        0                 0
(1.018, 1.023]     0              0  ...        0                 0
(1.023, 1.029]     0              0  ...        0                 0
(1.029, 1.034]     0              0  ...        0                 0
(1.034, 1.039]     1              1  ...        1                 1

[10 rows x 14 columns]

Now, let's find the mean of each of the columns for each ``density_group``.  *Notice* what happens to the non-numeric columns.

```
df.groupby(['density_group']).mean()
```

In [164]:
df.groupby(['density_group']).mean()

                fixed acidity  volatile acidity  ...   quality  alcohol fraction
density_group                                    ...
(0.987, 0.992]       6.580620          0.280219  ...  6.304565          0.118172
(0.992, 0.997]       7.153079          0.353889  ...  5.679012          0.102439
(0.997, 1.003]       8.186532          0.372192  ...  5.601934          0.095151
(1.003, 1.008]      11.877778          0.611111  ...  5.666667          0.103333
(1.008, 1.013]       7.900000          0.330000  ...  6.000000          0.088000
(1.013, 1.018]            NaN               NaN  ...       NaN               NaN
(1.018, 1.023]            NaN               NaN  ...       NaN               NaN
(1.023, 1.029]            NaN               NaN  ...       NaN               NaN
(1.029, 1.034]            NaN               NaN  ...       NaN               NaN
(1.034, 1.039]       7.800000          0.965000  ...  6.000000          0.117000

[10 rows x 13 columns]

You can specify a groupby using the names of table columns and compute other functions, such as the ``sum``, ``count``, ``std``, and ``describe``.

```
df.groupby(['density_group'])['residual sugar'].describe()
```

In [165]:
df.groupby(['density_group'])['residual sugar'].describe()

                 count       mean       std   min   25%   50%   75%    max
density_group
(0.987, 0.992]  1599.0   2.612477  1.822662   0.7   1.3   1.8   3.5  11.25
(0.992, 0.997]  3643.0   5.100796  3.769753   0.6   1.9   3.6   7.9  22.60
(0.997, 1.003]  1241.0   9.964988  6.042544   1.3   2.8  12.0  14.8  23.50
(1.003, 1.008]     9.0  11.755556  9.340485   3.7   4.2   6.6  15.4  26.05
(1.008, 1.013]     2.0  31.600000  0.000000  31.6  31.6  31.6  31.6  31.60
(1.013, 1.018]     0.0        NaN       NaN   NaN   NaN   NaN   NaN    NaN
(1.018, 1.023]     0.0        NaN       NaN   NaN   NaN   NaN   NaN    NaN
(1.023, 1.029]     0.0        NaN       NaN   NaN   NaN   NaN   NaN    NaN
(1.029, 1.034]     0.0        NaN       NaN   NaN   NaN   NaN   NaN    NaN
(1.034, 1.039]     1.0  65.800000       NaN  65.8  65.8  65.8  65.8  65.80

The simplest version of a groupby looks like this, and you can use almost any aggregation function you wish (mean, median, sum, minimum, maximum, standard deviation, count, etc.)

```
<data object>.groupby(<grouping values>).<aggregate>()
```

You can even group by multiple values: for example we can look at the quality grouped by the ``density_group`` and ``residual sugar``.

In [166]:
df.groupby(['residual sugar'])['quality'].describe()

                count      mean       std  min  25%  50%  75%  max
residual sugar
0.60              2.0  5.000000  0.000000  5.0  5.0  5.0  5.0  5.0
0.70              7.0  4.857143  1.069045  3.0  4.5  5.0  5.5  6.0
0.80             25.0  5.240000  0.925563  4.0  5.0  5.0  6.0  8.0
0.90             41.0  5.634146  0.829340  4.0  5.0  6.0  6.0  7.0
0.95              4.0  5.000000  0.000000  5.0  5.0  5.0  5.0  5.0
...               ...       ...       ...  ...  ...  ...  ...  ...
22.60             1.0  5.000000       NaN  5.0  5.0  5.0  5.0  5.0
23.50             1.0  5.000000       NaN  5.0  5.0  5.0  5.0  5.0
26.05             2.0  6.000000  0.000000  6.0  6.0  6.0  6.0  6.0
31.60             2.0  6.000000  0.000000  6.0  6.0  6.0  6.0  6.0
65.80             1.0  6.000000       NaN  6.0  6.0  6.0  6.0  6.0

[316 rows x 8 columns]

#### Exercise 3: Group-by

<ol>
<li>use <code>pd.cut</code> to perform a grouping of one or more of the dataframe columns
<li>use <code>groupby</code> to group by that (those) columns and then perform
<li>three different statistical summaries in three separate instances

In [177]:
# Cell for excercise 3

## 3.4 Lab for Functions and Pandas

Write a function that outputs the results of your exercise 3 code into a new dataframe. 

write your function so that the name of the columns to create categories for is a parameter, i.e.

`def my_summary_generator(column_name)`

In [178]:
# Cell for Lab 3.4